name: "Chromatic Deployment"

on: push

jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pnpm install
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
